name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Install premake
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"
        
    - name: Generate makefile with premake
      run: premake5 vs2022
      
    - name: Build solution with Debug
      run: msbuild Altrar.sln /property:Configuration=Debug
